### PR TITLE
Norminette fix

### PR DESCRIPTION
**Pull request by gitforodin**
I think this fixes norminette check.

### CODE REVIEW

**Comment by matteoolefloch** [comment]
Why you want to do this ?

**Comment by gitforodin** [comment]
To make the program work with subdirectories

**Comment by matteoolefloch** [comment]
The moulinette test '''KO''' if you use subdirectories

**Comment by gitforodin** [comment]
> Why you want to do this ?

This fixes norminette check if source code is in subdirectories.

**Comment by gitforodin** [comment]
> The moulinette test '''KO''' if you use subdirectories

If the my_config.sh is properly configured it should work with subdirectories

**Comment by SimplySka** [comment]
The moulinette don't compile your program if you are using subdirectories in libft... So you will automatically K.O and failed because you're using subdirectories, but up to you..

**Comment by gitforodin** [comment]
> The moulinette don't compile your program if you are using subdirectories in libft... So you will automatically K.O and failed because you're using subdirectories, but up to you..

I didn't knew that, so i have source files in a srcs subdirectory and header file in includes subdirectory, i was using Piscine C09 as an example. Thank you

**Pull request closed without merging**
